name: test

on:
  push: {}
  pull_request:
    types: [created, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@master
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: |
          npm -g install pnpm
          pnpm install
          pnpm tsc
